### ISSUE TITLE
Implement component which supports WebSocket

### ISSUE THREAD

**Issue by siemieniuk** [akai-org/love_letter#2]
- connect to the game
- ability to react to received messages
- ability to send messages to the server

**Comment by mit3r** [comment]
According to doc file, I wonder if a better solution would be to send at least the initial game state to the frontend as JSON.  Multiple messages could cause multiple renders. 

Another issue is situation when the message doesn't arrive or the connection is slow.

Single state message is easier to handle. Front gets game state and set view based on it. 

Next to state messages could exist event messages which can cause animations, example: { event: 'killed', payload: 'player1' }

I'm open to discussion. Cause imo it is one of the most important issues.

**Comment by siemieniuk** [comment]
> According to doc file, I wonder if a better solution would be to send at least the initial game state to the frontend as JSON. Multiple messages could cause multiple renders.
> 
> Another issue is situation when the message doesn't arrive or the connection is slow.
> 
> Single state message is easier to handle. Front gets game state and set view based on it.
> 
> Next to state messages could exist event messages which can cause animations, example: { event: 'killed', payload: 'player1' }
> 
> I'm open to discussion. Cause imo it is one of the most important issues.

Yeah, that sounds really nice! Let's think about it in the next meeting!
